### ISSUE TITLE
Intall DLLs

### ISSUE THREAD

**Issue by israteneda** [alessandroTironi/Unity-DialogflowV2Agents#7]
Hello @alessandroTironi thanks for share your library.

I want to try the library but I can't since I didn't find the (Syrus.Plugins.DialogflowV2Agents.dll) and Newtonsoft.Json.dll DLLs.

Where can I search these dlls.

**Comment by alessandroTironi** [comment]
Hi @israteneda 
Did you download the project from the Releases sections? The binaries from that page are outdated, so you should get a working proejct by just cloning it on your machine. The Netwonsoft.Json.dll is in the Assets/Plugins folder, while if you are interested into extracting the latest Syrus.Plugins.DialogflowV2Agents.dll you can let Unity build it and find it in Library/ScriptAssemblies generated folder.

**Comment by alvarocaiza** [comment]
Hello, thanks for such a great plugin. Since they changed to V2, I couldn't find anything that would help me connect my chatbot with unity.

I have tested with my own, it works, however, any idea why the voice is the same (standard male voice) even after I have changed the TTS settings in my Dialogflow console? 

In the console it shows me the output audio as I have set (female voice with UK accent) but in the Unity project is still a male voice. Please let me know if you have any ideas of what could be the issue here.

Once again, legend, thanks so much.
